spring:
  h2-console:
    enabled: true
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:h2:mem:testdb
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true



